### ISSUE TITLE
headers don't change font size 

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/ebook#15]
Logging bugs to be fixed.  kd_render.rb/convert_header() does not use the header level number to set the Shoes font size (or method). Just a trivial case when?

**Comment by IanTrudel** [comment]
Use `el.options[:level]`.

**Comment by ccoupe** [comment]
It's late at night. For some reason this doesn't work
```ruby
     def convert_header(el)
        #%{para(strong("#{el.options[:raw_text]}\n"), :margin_left => 6, :margin_right => gutter)}
        case el.options[:level]
        when 1
          %{subtitle(strong("#{el.options[:raw_text]}"), :margin_left => 6, :margin_right => gutter)}
        when 2
          %{tagline(strong("#{el.options[:raw_text]}"), :margin_left => 6, :margin_right => gutter)}
        when 3
          %{caption(strong("#{el.options[:raw_text]}"), :margin_left => 6, :margin_right => gutter)}
        else
          %{para(strong("#{el.options[:raw_text]}"), :margin_left => 6, :margin_right => gutter)}
        end
      end
```
I clearly don't understand Ruby's case/when,

Removing that extra `\n` in the header does help #13

**Comment by IanTrudel** [comment]
What kind of Shoes code is generated from that case/when? Checking the output prior its **rendering** would help.

**Comment by IanTrudel** [comment]
Your code actually works well here.

![image](https://cloud.githubusercontent.com/assets/8844578/21624976/734cbf30-d1d7-11e6-8ee7-a76515fe24ab.png)

Take a look at generated code (only the headers):

```ruby
subtitle(strong("Header"), :margin_left => 6, :margin_right => gutter)
tagline(strong("Subheader"), :margin_left => 6, :margin_right => gutter)
caption(strong("Sub-sub header"), :margin_left => 6, :margin_right => gutter)
```

**Comment by IanTrudel** [comment]
Header sizes should be configurable in the YAML file.

**Comment by ccoupe** [comment]
That's one reason I wrote the re-write the code that way. kd-render thas the yaml settings in the @cfg var. It's possible to change the font too. Just waiting until all the important stuff is working.

**Comment by IanTrudel** [comment]
Very good. No hurry. It's all about documenting what needs to be done anyway.

**Comment by ccoupe** [comment]
This one can be closed. I think.
