### ISSUE TITLE
Codespan blocks not working.

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/ebook#9]

**Comment by IanTrudel** [comment]
Below is a sample Markdown file for **codespan** and **codeblock**. It yields the following output with 
a modified [Kramdown001.rb](https://github.com/Shoes3/ebook/blob/master/kramdown001.rb).

```
<kd:codespan "code" nil {:location=>5}>
<kd:codespan "back-ticks around" nil {:location=>5}>
<kd:codespan "javascript\nvar s = \"JavaScript syntax highlighting\";\nalert(s);\n" nil {:location=>7}>
<kd:codeblock "This is a code block.\n" nil {:location=>16}>
```


Kramdown001.rb modifications:
```ruby
def convert_codespan(el)
   pp el
end

def convert_codeblock(el)
   pp el
end
```

Markdown file: [codespan_block.zip](https://github.com/Shoes3/ebook/files/678219/codespan_block.zip)
